package day52_exception2;

public class Main {
    public static void main(String[] args) {

try {
    System.out.println(9/0);
}catch (ArithmeticException e){

}

        System.out.println("Completed");

    }
}
